version: '3.6'

services:
  zk-1:
    image: confluentinc/cp-zookeeper:5.5.0
    container_name: zk-1
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888
      KAFKA_OPTS: -Dzookeeper.admin.enableServer=false -Dzookeeper.4lw.commands.whitelist=stat
    network_mode: host

  zk-2:
    image: confluentinc/cp-zookeeper:5.5.0
    container_name: zk-2
    depends_on:
      - zk-1
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888
      KAFKA_OPTS: -Dzookeeper.admin.enableServer=false -Dzookeeper.4lw.commands.whitelist=stat
    network_mode: host

  zk-3:
    image: confluentinc/cp-zookeeper:5.5.0
    container_name: zk-3
    depends_on:
      - zk-2
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 42181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888
      KAFKA_OPTS: -Dzookeeper.admin.enableServer=false -Dzookeeper.4lw.commands.whitelist=stat
    network_mode: host

  kafka-1:
    image: confluentinc/cp-kafka:5.4.4
    container_name: kafka-1
    network_mode: host
    depends_on:
      - zk-1
      - zk-2
      - zk-3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:19092

  kafka-2:
    image: confluentinc/cp-kafka:5.4.4
    container_name: kafka-2
    network_mode: host
    depends_on:
      - zk-1
      - zk-2
      - zk-3
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092

  kafka-3:
    image: confluentinc/cp-kafka:5.4.4
    container_name: kafka-3
    network_mode: host
    depends_on:
      - zk-1
      - zk-2
      - zk-3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:39092

  schema-registry:
    image: confluentinc/cp-schema-registry:6.2.0
    depends_on:
      - zk-1
      - zk-2
      - zk-3
      - kafka-1
      - kafka-2
      - kafka-3
    container_name: schema-registry
    network_mode: host
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'localhost:22181'
